### PR TITLE
Pull request for BT3103 Discovery Path

### PR DESCRIPTION
**Pull request by JoleneTansm**

### CODE REVIEW

**Comment by JoleneTansm** [comment]
For teaching purposes.

**Comment by shivin9** [comment]
Hi can you remove the extra files which have got committed in the .idea folder?
Also, please retain the README as it is.

**Comment by shivin9** [comment]
There are many files still remaining, please delete them also. In the end you should have only 2 extra files.

**Comment by JoleneTansm** [comment]
Hi, can i close this pull request if my new pull request has been merged?

**Comment by shivin9** [comment]
Yes

**Pull request closed without merging**
