### PR TITLE
Jed branch

### PR DESCRIPTION
**Pull request by jedlwk**

### CODE REVIEW

**Comment by jedlwk** [comment]
Help me T_T

**Comment by shivin9** [comment]
Hi,

Where do you need help?

**Comment by jedlwk** [comment]
Hi Mr Shivin,

May I know if I have completed the Discovery Task?

Thank you!

**Comment by shivin9** [comment]
No. You need to try the merge conflict exercises. In the end, your PR should look like https://github.com/shivin9/BT3103/pull/62.

**Pull request closed without merging**
