### PR TITLE
Introduction

### PR DESCRIPTION
**Pull request by XingYing99**

### CODE REVIEW

**Comment by shivin9** [comment]
Also, please add the introduction file.

**Comment by shivin9** [comment]
Hi, Can you resolve the merge conflicts?

**Comment by XingYing99** [comment]
I tried to add a new introduction file in my local bt3103 repository but
after try to push changes , my BT3103 repository in github was not updated.
May i ask what could be the reasons?

**Comment by shivin9** [comment]
Please double check that you are pushing the right branch.

**Comment by XingYing99** [comment]
I think i have pushed the wrong branch before, i have sent a new pull
request.
Thank you

**Pull request closed without merging**
