### PR TITLE
Updated personal introduction

### PR DESCRIPTION
**Pull request by ameliayamato**

### CODE REVIEW

**Comment by shivin9** [comment]
Hi, did you try the merge conflict exercises? I cannot see that in your conflict history.

**Comment by ameliayamato** [comment]
Hi, I believe that I had tried them! Are you able to see it now?

**Comment by shivin9** [comment]
No I can't see them. Also, add the file which has your ID.

**Comment by shivin9** [comment]
Maybe you need to push it on github.

**Comment by ameliayamato** [comment]
Hi, I just did it again, I think it should be seen now. Thank you.

**Pull request closed without merging**
