### PR TITLE
Week 6 GitHub Path

### PR DESCRIPTION
**Pull request by Mochihaha**

### CODE REVIEW

**Comment by shivin9** [comment]
Did you try the merge conflicts and PR exercise?

**Comment by Mochihaha** [comment]
I did the merge conflicts exercise but not on the BT3103 repository but on my test-repo.
I didn't know we had to do those in the introduction branch because the instruction did not mention that we had to do merge conflict in the introduction branch of the BT3103 repository as shown:
image

Should I do the merge conflict in my BT3103 Introduction branch and then merge the Introduction branch with my master branch then push the changes my master branch? After this, do I have to create a new pull request to you?

As for the PR exercise,I'm not very sure which exercise you are referring to because the PR exercise on Discovery is to do this Introduction branch and create a PR to you. Additionally, you are also providing feedback for me now so this covers the 'Incorporating feedback in your pull request' exercise. 
Thank you.

**Comment by Mochihaha** [comment]
Also, may I ask if the NUS ID refers to the one starting with A or E?

**Comment by shivin9** [comment]
NUS ID is the one starting with 'A'

**Comment by Mochihaha** [comment]
Hi Shivin, I think the README.md has been changed and is no longer the same as when I first forked it from shivin9/BT3103, so I think it might cause some merge conflicts for some of us later on when we try to create a pull request. Could you help us check the README.md file?

**Comment by shivin9** [comment]
No problem. You'll have to first pull in the changes in your local repo and then make a PR. This is a normal situation in collaborative projects in which you'll have to work in the future.

**Comment by Mochihaha** [comment]
ok thank you!

**Comment by Mochihaha** [comment]
I made a new pull request because it was getting very messy so I closed this one.

**Pull request closed without merging**
