### PR TITLE
Introduction

### PR DESCRIPTION
**Pull request by dillonchew**

### CODE REVIEW

**Comment by shivin9** [comment]
Hi, did you try the merge conflict exercises? I cannot see that in your commit history.

**Comment by dillonchew** [comment]
Hi Prof,

I think I missed it sorry! I just did the path exercise. Are you able to
view it?

Thank you,
Dillon

**Comment by shivin9** [comment]
No I still can't see it. Please push these updates here.

**Comment by dillonchew** [comment]
I have submitted a new pull request

**Pull request closed without merging**
