### PR TITLE
Yang Junhan's New File #2

### PR DESCRIPTION
**Pull request by junhanyang96**

### CODE REVIEW

**Comment by shivin9** [comment]
Can you add your introduction? Also, please modify the readme so that it looks like the readme on the repository.

**Comment by junhanyang96** [comment]
Hi do you mean the NUS ID file or the introduction part in the ID file? Cos I do have the NUS ID file. But I will add the introduction into it.

**Comment by shivin9** [comment]
I meant the NUS ID file only.

**Comment by junhanyang96** [comment]
Hi sorry just to clarify, you cannot see my NUS ID file? Cos I have it there. It is in the commit"new file with ID" above.

**Comment by shivin9** [comment]
Every student is supposed to make two files like this:
https://github.com/shivin9/BT3103/pull/66/files

**Pull request merged**
